region: us-east-1

function_name: hello_lambda
handler: service.handler
role: lambda_execution_role
description: trying out this python-lambda toolkit thing

# dist_directory: dist
timeout: 15
memory_size: 128
